version: "3.4"

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: production
      DATABASE_HOST: notes-postgres
      DATABASE_NAME: notes
      DATABASE_USERNAME: notes
      DATABASE_PASSWORD: notes
    ports:
      - 1337:1337
    networks:
      - notes-backend-network
    depends_on:
      - notes-postgres

  notes-postgres:
    image: postgres
    restart: always
    container_name: notes-postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
      POSTGRES_DB: notes
    volumes:
      - data:/data/db
    ports:
      - 5432:5432
    networks:
      - notes-backend-network

volumes:
  data:

networks:
  notes-backend-network:
